config/routes.rb
HopeTest::Application.routes.draw do

  resources :admins

  resources :documents

  resources :links

  get "users/new"

  get '/about' => 'static_pages#about'

  get '/contact' => 'messages#new'

  resources :groups

  match '/events/search' => 'events#search', :method => 'post'

  match '/events/print' => 'events#print', :method => 'get'

  resources :events

  resources :users

  resources :links

  resources :sessions, only: [:new, :create, :destroy]

  resources :messages, only: [:new, :create]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'#, via: :delete

  get '/home' => 'static_pages#about'
  root :to => 'static_pages#about'

end

app/views/shared/_notice.html.erb
<% flash.each do |key, value| %>
	<span id="notice-wrapper">
	    <p id="notice"><%= value %></p>
	</span>
 <% end %>

app/views/shared/_top_links.html.erb
<div class="top-links">
          <div class="links_container">
            <%= link_to "LINKS", links_path %>
            <%= link_to "CONTACT", contact_path %>
            <%= link_to "PEER LED GROUPS", groups_path %>
            <%= link_to "WHAT'S ON", events_path %>
            <%= link_to "NEW HOPE", about_path %>
            <% if admin %>
            <%= link_to "ADMIN", admins_path %>
              <%= link_to "Sign Out", signout_path %>
            <% end %>
          </div>
      </div>

app/views/shared/_top_title.html.erb
<div class="top-title">
          <%= image_tag("logo.png") %>
          <!-- <h2>Making a difference in Mental Health </h2> -->
      </div>