config/routes.rb
HopeTest::Application.routes.draw do

  resources :admins

  resources :documents

  resources :links

  get "users/new"

  get '/about' => 'static_pages#about'

  get '/contact' => 'messages#new'

  resources :groups

  match '/events/search' => 'events#search', :method => 'post'

  match '/events/print' => 'events#print', :method => 'get'

  resources :events

  resources :users

  resources :links

  resources :sessions, only: [:new, :create, :destroy]

  resources :messages, only: [:new, :create]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'#, via: :delete

  get '/home' => 'static_pages#about'
  root :to => 'static_pages#about'

end

app/models/event.rb
require 'event_display_helper'
require 'event_date_helper'
require 'events_refinement_helper'

class Event < ActiveRecord::Base

  include EventDisplayHelper
  include EventDateHelper
  extend EventsRefinementHelper

  attr_accessible :name, :organisation, :description, :contact_person, :contact_role, :phone, :email, :address_id,
                  :website,:contact_id, :cost, :access, :access_details, :complex_date_id,
                  :referral_id, :joining_process, :directions_car, :directions_walking, :directions_bus, :directions_train,
                  :other, :tagset_attributes, :targetset_attributes, :address_attributes, :complex_date_attributes
  belongs_to :referral
  belongs_to :contact
  has_one :address
  has_one :complex_date
  has_one :tagset
  has_one :targetset
  accepts_nested_attributes_for :tagset, :targetset, :address, :complex_date

  validates :name, :presence => true
  validates :organisation,  :presence => true
  validates :cost, :presence => true
  validates :access,  :presence => true
  validates :referral_id, :presence => true

  scope :for_tag, lambda{|tag| joins(:tagset).where(tag + ' = ?',  true)}
  scope :for_target, lambda{|target| joins(:targetset).where(target + ' = ?',  true)}

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  before_filter :verify_is_admin, :only => [:new, :edit, :create, :update, :destroy]
  after_filter :record_update, :only => [:create, :update, :destroy]


  def search

    @search = Search.new
    @events = Event.get_events(params, admin)

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @event, status: :created, location: @event }
    end
  end

  def print
    @events = Event.find params[:events]

    respond_to do |format|
      format.html {render layout: false}
      format.json { render json: @event, status: :created, location: @event }
    end
  end

  def index
    @search = Search.new
    @events = Event.get_events(params, admin)
    if params[:event]
      p = params[:event]
      @mem = {:tag => p[:tag], :target => p[:target], :referral => p[:referral], }
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new

      @event = Event.new
      @event.tagset = Tagset.new
      @event.targetset = Targetset.new
      @event.address = Address.new
      @event.complex_date = ComplexDate.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @event }
      end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])


    respond_to do |format|
      if @event.save
        puts "SUCESS"
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        puts "FAILURE"
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end




end

private
def verify_is_admin
  if admin
    return
  else
    redirect_to events_path
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_cost_drop_down.erb
<select name="cost">
  <option value=""      <%= params[:cost] == nil ? "selected ='selected'" : "false" %> >Cost</option>
  <option value="free"     <%= params[:cost] == 'free' ? "selected ='selected'" : "false" %> >Free</option>
  <option value="less"     <%= params[:cost] == 'less' ? "selected ='selected'" : "false" %>>Less than £5</option>
  <option value="more"     <%= params[:cost] == 'more' ? "selected ='selected'" : "false" %>>More than £5</option>
</select>

app/views/events/_date_drop_down.erb
<select name="quick_date">
  <option value=""      <%= params[:quick_date] == nil ? "selected ='selected'" : "false" %> >Quick Date</option>
  <option value="day"     <%= params[:quick_date] == 'day' ? "selected ='selected'" : "false" %> >Today</option>
  <option value="week"     <%= params[:quick_date] == 'week' ? "selected ='selected'" : "false" %>>This week</option>
  <option value="month"     <%= params[:quick_date] == 'month' ? "selected ='selected'" : "false" %>>This month</option>
</select>

app/views/events/_form.html.erb
<div class="row">
  <div>
    <%= simple_form_for @event, :defaults => { :input_html => { :class => 'span6' } }, :html => {:class => 'form-horizontal'} do |f| %>

    <ul class="nav nav-tabs" >
    <li class="active"><a href="#basic" data-toggle="tab">Basic Details</a></li>
    <li><a href="#address" data-toggle="tab">Address</a></li>
    <li><a href="#contact" data-toggle="tab">Contact</a></li>
    <li><a href="#date" data-toggle="tab">Date and Time</a></li>
    <li><a href="#further" data-toggle="tab">Further Details</a></li>
    <li><a href="#target" data-toggle="tab">Target</a></li>
    <li><a href="#tag" data-toggle="tab">Tags</a></li>
    <li><a href="#directions" data-toggle="tab">Directions</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="basic">

        <%= f.input :name, :input_html => { :class => 'span8' } %>
        <%= f.input :organisation %>
        <%= f.input :description, :as => :text, :input_html => { :rows => 3 } %>
    </div>


    <div class="tab-pane" id="address">

      <%= f.simple_fields_for :address do |a| %>

           <%= a.input :number, :label => "House Number / Name"  %>
           <%= a.input :street, :label => "Street"  %>
           <%= a.input :district, :label => "Town / City"  %>
           <%= a.input :county, :label => "County"  %>
           <%= a.input :postcode, :label => "Postcode"  %>

        <% end %>

    </div>

    <div class="tab-pane" id="contact">

      <%= f.input :contact_person %>
        <%= f.input :contact_role %>
        <%= f.input :phone %>
        <%= f.input :email %>

        <%= f.association :contact, :as => :select, :input_html => { :class => 'event-select' } %>

    </div>

    <div class="tab-pane" id="date">

      <%= f.simple_fields_for :complex_date do |d| %>

          <!-- <%= d.association :date_type, :label => "Type of date", :as => :select  %> -->
          <%= d.association :date_type,  :as => :hidden, :input_html => { :value => "1" } %>

          <%= d.input :fixed_date, :label => "Date"  %>

          <%= d.input :time, :label => "Time"  %>

          <!-- <%= d.association :offset_type, :label => "Type of offset", :as => :select  %> -->

          <!-- <%= d.association :fixed_offset, :label => "Fixed Offset", :as => :select  %> -->

          <!-- <%= d.association :dynamic_offset, :label => "Dynamic Offset", :as => :select  %> -->

          <!-- <%= d.association :frequency, :label => "Dynamic Frequency", :as => :select  %> -->

          <!-- <%= d.association :fixed_frequency, :label => "Fixed Frequency", :as => :select  %> -->

          <!-- <%= d.association :day, :label => "Day", :as => :select  %> -->

        <% end %>

    </div>

    <div class="tab-pane" id="further">

      <%= f.input :cost %>

        <%= f.input :access, :as => :select, :label => "Disabled access", :input_html => { :class => 'event-select' }  %>

        <%= f.input :access_details %>

        <%= f.association :referral, :as => :select, :input_html => { :class => 'event-select' }   %>
        <%= f.input :joining_process %>



    </div>

    <div class="tab-pane" id="target">

      <%= f.simple_fields_for :targetset do |t| %>
        <div class="row">
          <div class="span4">
              <%= t.input :adults, :as => :boolean, :label => "Adults over 18" %>
              <%= t.input :under_18, :as => :boolean, :label => "People under 18"  %>
              <%= t.input :men, :as => :boolean, :label => "Men"  %>
              <%= t.input :women, :as => :boolean, :label => "Women"  %>
              <%= t.input :mental_health, :as => :boolean, :label => "People with mental health issues"  %>
              <%= t.input :learning_difficulties, :as => :boolean, :label => "People with learning difficulties"  %>
          </div>
          <div class="span4 offset1">
              <%= t.input :drug_alcohol, :as => :boolean, :label => "People with Drug / Alcohol Issues"  %>
              <%= t.input :homelessness, :as => :boolean, :label => "People with homelessness issues"  %>
              <%= t.input :carers, :as => :boolean, :label => "Carers"  %>
              <%= t.input :carers_mental_health, :as => :boolean, :label => "Carers for people with mental health issues"  %>
              <%= t.input :vulnerable, :as => :boolean, :label => "Vulnerable people"  %>
              <%= t.input :anyone, :as => :boolean, :label => "Anyone"  %>
          </div>
        </div>
              <%= t.input :other, :as => :string %>
        <% end %>

    </div>

    <div class="tab-pane" id="tag">

      <%= f.simple_fields_for :tagset do |t| %>
        <div class="row">
          <div class="span4">
            <%= t.input :sports, :as => :boolean, :label => "Sports and Games"  %>
            <%= t.input :outdoors, :as => :boolean, :label => "Outdoors activities"  %>
            <%= t.input :creative, :as => :boolean, :label => "Creative Arts"  %>
            <%= t.input :wellbeing, :as => :boolean, :label => "Health and Wellbeing"  %>
            <%= t.input :social, :as => :boolean, :label => "Social activities"  %>
          </div>
          <div class="span4 offset1">
            <%= t.input :faith, :as => :boolean, :label => "Faith"  %>
            <%= t.input :food, :as => :boolean, :label => "Food and Drink"  %>
            <%= t.input :learning, :as => :boolean, :label => "Learning"  %>
            <%= t.input :exercise, :as => :boolean, :label => "Fitness and exercise"  %>
            <%= t.input :lifestyle, :as => :boolean, :label => "Lifestyle"  %>
          </div>
        </div>
            <%= t.input :other, :as => :string %>
        <% end %>

    </div>

    <div class="tab-pane" id="directions">

      <%= f.input :directions_walking %>
        <%= f.input :directions_bus %>
        <%= f.input :directions_train %>
        <%= f.input :directions_car %>

        <%= f.input :other%>

    </div>




      </div>

        <%= f.button :submit, :class => 'btn-primary btn-large event-create', :id =>  'event-submit'  %>

        <%= link_to 'Back', events_path, :class => 'btn-success btn-large event-back' %>


    <% end %>
  </div>
</div>

app/views/events/_referral_drop_down.erb
<select name="referral">
  <option value=""      <%= params[:referral] == nil ? "selected ='selected'" : "false" %> >Referral Type</option>
  <option value="1"     <%= params[:referral] == '1' ? "selected ='selected'" : "false" %> >GP / Professional</option>
  <option value="2"     <%= params[:referral] == '2' ? "selected ='selected'" : "false" %>>Self Refferal</option>
  <option value="3"     <%= params[:referral] == '3' ? "selected ='selected'" : "false" %>>Other</option>
</select>

app/views/events/_single_event.erb
<div class='event-entry' onclick="toggleDetails(<%= event.id.to_s %>)">
  <div class="<%= 'event-summary_' + event.id.to_s %>">
    <span class='summary-datetime'>
      <span class='summary-date'><%= event.summary_date %></span>

      <span class='summary-time'><%= event.summary_time %></span>
    </span>
    <span class='summary-nameaddress'>
      <span class='summary-name'><%= event.summary_name %></span>

      <span class='summary-address'>
        <span>
          <%= event.summary_address_line_one %>
        </span>
      </br>
        <span>
          <%= event.summary_address_postcode %>
        </span>
      </span>
    </span>
    <span class='summary-right'>
      Cost: <span class='summary-cost'><%= event.summary_cost %></span>
    </br>
      Contact: <span class='summary-contact'><%= event.summary_contact %></span>
    </span>
  </div>



  <div class="<%= 'event-details_' + event.id.to_s %>" hidden='true'>
   <h4><%= event.summary_name %></h4>
   <p> <strong>Organisation: </strong> <%= event.display_organisiation %></p>

   <div>
     <span class='details-date'> <strong>Details: </strong> <%= event.summary_date %></span> -
     <span class='details-time'><%= event.summary_time %></span> |
     <span><%= event.cost %></span> |
     <span><%= event.address.town %></span> |
     <span><%= event.display_access %></span>
   </div>
<br>
   <p> <strong>Full Address: </strong> <%= event.summary_address %></p>
   <p> <strong>Contact: </strong> <%= event.contact_person %> | <%= event.display_contact %> </p>
   <p>  <strong>Joining: </strong> <%= event.joining_process %> </p>
   <p> <strong>Description: </strong> <%= event.display_description %></p>
   <% if event.display_directions_car?  %>
   <p> <strong>Directions (Car): </strong> <%= event.display_directions_car %></p>
  <% end %>
  <% if event.display_directions_walking?  %>
   <p> <strong>Directions (walking): </strong> <%= event.display_directions_walking %></p>
  <% end %>
  <% if event.display_directions_bus?  %>
   <p> <strong>Directions (bus): </strong> <%= event.display_directions_bus %></p>
  <% end %>
  <% if event.display_directions_train?  %>
   <p> <strong>Directions (train): </strong> <%= event.display_directions_train %></p>
  <% end %>
   <% if admin %>

       <span><%= link_to "Click here to EDIT #{event.name}", edit_event_path(event),
                        :class => 'btn btn-primary btn-mini event-edit'      %></span>

       <span><%= link_to "Click here to DELETE #{event.name}", event,
              :class => 'btn btn-danger btn-mini event-delete',
              method: :delete,
              data: { confirm: 'Are you sure?' } %></span>

   <% end %>
  </div>
</div>

app/views/events/_single_event_2.erb
 <div class='event-entry' onclick="toggleDetails(<%= event.id.to_s %>)">
<div class="<%= 'event-summary_' + event.id.to_s %>">
  
       <span style="margin-right: 10px;"><%= event.complex_date.time == nil ? 'Unknown' : event.complex_date.time.strftime("%b %e, %l:%M %p") %></span> | 
   
       <span style="margin-right: 10px;margin-left: 10px; font-weight: bold;"><%= event.name == '' ? 'Unknown' : event.name %></span> |
<span><%= event.display_address %></span> | 
    <span style="float:right; margin-right:5px;">
       Cost: <span><%= event.cost  == '' ? 'Unknown' : event.cost %></span> |
  
      Contact: <span><%= event.contact_person  == '' ? 'Unknown' : event.contact_person %></span>
      </span>
   </div>



<div class="<%= 'event-details_' + event.id.to_s %>" hidden='true'>
   <h3><%= event.name == '' ? 'Unknown' : event.name %> - <%= event.organisation  == '' ? '' : event.organisation %></h3>
   <p><%= event.description == '' ? 'Unknown' : event.description %></p>
</div>
</br>

   <% if admin %>
     <div class="row">
       <div class="span6">
       <span><%= link_to "Click here to EDIT #{event.name}", edit_event_path(event), 
                        :class => 'btn btn-primary btn-block event-edit'      %></span>
       </div>
       <div class="span6">
       <span><%= link_to "Click here to DELETE #{event.name}", event,
              :class => 'btn btn-danger btn-block event-delete', 
              method: :delete, 
              data: { confirm: 'Are you sure?' } %></span>
       </div>
     </div>
   <% end %>

   
 </div>

<script type="text/javascript" charset="utf-8">
 function toggleDetails(id){

   $('.event-summary_' + id).toggle();

   $('.event-details_' + id).toggle();
 };
</script>

app/views/events/_tag_drop_down.erb
<select name="tag">
  <option value=""           <%= params[:tag] == nil ? "selected ='selected'" : "false" %> >Categories</option>
  <option value="arts"       <%= params[:tag] == 'arts' ? "selected ='selected'" : "false" %> >Arts</option>
  <option value="sports"     <%= params[:tag] == 'sports' ? "selected ='selected'" : "false" %>>Sports</option>
  <option value="outdoors"   <%= params[:tag] == 'outdoors' ? "selected ='selected'" : "false" %>>Outdoors</option>
  <option value="creative"   <%= params[:tag] == 'creative' ? "selected ='selected'" : "false" %>>Creative</option>
  <option value="wellbeing"  <%= params[:tag] == 'wellbeing' ? "selected ='selected'" : "false" %>>Wellbeing</option>
  <option value="social"     <%= params[:tag] == 'social' ? "selected ='selected'" : "false" %>>Social</option>
  <option value="faith"      <%= params[:tag] == 'faith' ? "selected ='selected'" : "false" %>>Faith</option>
  <option value="food"       <%= params[:tag] == 'food' ? "selected ='selected'" : "false" %>>Food</option>
  <option value="learning"   <%= params[:tag] == 'learning' ? "selected ='selected'" : "false" %>>Learning</option>
  <option value="exercise"   <%= params[:tag] == 'exercise' ? "selected ='selected'" : "false" %>>Exercise</option>
  <option value="lifestyle"  <%= params[:tag] == 'lifestyle' ? "selected ='selected'" : "false" %>>Lifestyle</option>
</select>

app/views/events/_target_drop_down.erb
<div class="search-target">
  
<div>
<input type='checkbox' name="target[adults]" value="1"                <%= "checked='true'" if params[:target] and params[:target][:adults] == '1' %> >Adults</input>
</div>
<div>
<input type='checkbox' name="target[under_18]"  value="1"               <%= "checked='true'" if params[:target] and params[:target][:under_18] == '1' %> >Under 18's</input>
</div>
<div>
  <input type='checkbox' name="target[men]"  value="1"                  <%= "checked='true'" if params[:target] and params[:target][:men] == '1' %>>Men</input>
  </div>
<div>
<input type='checkbox' name="target[women]"  value="1"                  <%= "checked='true'" if params[:target] and params[:target][:women] == '1' %>>Women</input>
</div>
<div>
<input type='checkbox' name="target[mental_health]" value="1"           <%= "checked='true'" if params[:target] and params[:target][:mental_health] == '1' %>>Mental Health Issues</input>
</div>
<div>
<input type='checkbox' name="target[learning_difficulties]" value="1"  <%= "checked='true'" if params[:target] and params[:target][:learning_difficulties] == '1' %>>Learning difficulties</input>
</div>
<div>
<input type='checkbox' name="target[drug_alcohol]"  value="1"           <%= "checked='true'" if params[:target] and params[:target][:drug_alcohol] == '1' %>>Drug alcohol problems</input>
</div>
<div>
<input type='checkbox' name="target[homelessness]" value="1"            <%= "checked='true'" if params[:target] and params[:target][:homelessness] == '1' %>>Homelessness</input>
</div>
<div>
<input type='checkbox' name="target[carers]"   value="1"               <%= "checked='true'" if params[:target] and params[:target][:carers] == '1' %>>Carers</input>
</div>
<div>
<input type='checkbox' name="target[carers_mental_health]" value="1"   <%= "checked='true'" if params[:target] and params[:target][:carers_mental_health] == '1' %>>Carers (mental health)</input>
</div>
<div>
<input type='checkbox' name="target[vulnerable]"    value="1"          <%= "checked='true'" if params[:target] and params[:target][:vulnerable] == '1' %>>Vulnerable people</input>
</div>
<div>
<input type='checkbox' name="target[anyone]"    value="1"              <%= "checked='true'" if params[:target] and params[:target][:anyone] == '1' %>>Anyone</input>
</div>

</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<span class="event-links">
  <form action="<%= events_search_path %>" method="post">

    <h5>Date</h5>
    <span class='search-filters'>
      <%= render :partial => 'date_drop_down' %>
    </span>


    <div class="input-prepend">
      <input class='search-datepicker' type="text" name='date' data-behaviour='datepicker'>
      <span class="add-on"><i class="icon-calendar"></i></span>
    </div>


    <h5>Filters</h5>


    <span class='search-filters'>

    <%= render :partial => 'cost_drop_down' %>
    <%= render :partial => 'referral_drop_down' %>
    <%= render :partial => 'tag_drop_down' %>
    <%= render :partial => 'target_drop_down' %>

    </span>

    <button class="btn btn-success" >Search</button>
    <a href="<%= events_path %>" class="btn btn-warning">Reset</a>

  </form>




</span>


  <h1 class='page-title'>What's On - <%= DateTime.now.to_date.strftime(('%e %B %Y')) %></h1>

  <%= link_to events_print_path(:events => @events), :class => "btn btn-primary btn-mini print-button" do %>
    Print <span class="add-on"><i class="icon-print"></i></span>
  <% end %>

  <span style="margin-left: 10px; float: right;"> Click on an entry to display extra information and details</span>
  <span style="margin-left: 10px; float: right;"> To add an event <%= link_to "contact us", contact_path, :class => "contact-link" %></span>
<% if admin %>
    <span style="margin-left: 10px; float: right;"><%= link_to 'New Event', new_event_path, :class => 'btn btn-success btn-mini event-new' %></span>
  <% end %>

<div class="event-list">
  <% @events.each do |event| %>
    <%= render :partial => 'single_event', :locals => {:event => event} %>
  <% end %>




</div>




<br />





<script type="text/javascript" charset="utf-8">


$("[data-behaviour~='datepicker']").datepicker({
    "format": "yyyy-mm-dd",
    "weekStart": 1,
    "autoclose": true
});



</script>

app/views/events/new.html.erb
<!-- <h1>New event</h1> -->

<%= render 'form' %>

<!-- <%= link_to 'Back', events_path %> -->

app/views/events/print.html.erb
<h1>What's on</h1>

<div class="event-list">
  <% @events.each do |event| %>
    <h3><%= event.name %> ( <%= event.summary_date %> <%= event.summary_time %> )</h3>
    <span><strong>Address: </strong><%= event.summary_address %></span> <br>
    <span><strong>Contact: </strong><%= event.summary_contact %></span>
    <span>(<%= event.display_contact %>)</span><br>
    <span><strong>Cost: </strong><%= event.summary_cost %></span>
    <p><strong>Description: </strong><%= event.description %></p>
	
  <% end %>

  
</div>

app/views/events/show.html.erb
<%= render :partial => "shared/notice" %>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>