config/routes.rb
HopeTest::Application.routes.draw do

  resources :admins

  resources :documents

  resources :links

  get "users/new"

  get '/about' => 'static_pages#about'

  get '/contact' => 'messages#new'

  resources :groups

  match '/events/search' => 'events#search', :method => 'post'

  match '/events/print' => 'events#print', :method => 'get'

  resources :events

  resources :users

  resources :links

  resources :sessions, only: [:new, :create, :destroy]

  resources :messages, only: [:new, :create]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'#, via: :delete

  get '/home' => 'static_pages#about'
  root :to => 'static_pages#about'

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :description, :document_type_id, :name, :document_link
  belongs_to :document_type
  has_attached_file :document_link,
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml")

  validates :name, :presence => true
  validates :document_link, :presence => true

  def doc_type
  	DocumentType.find(document_type_id).title
  end
end

app/models/document_type.rb
class DocumentType < ActiveRecord::Base
  attr_accessible :position, :title
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= simple_form_for 	@document, :html => {:class => 'document-form'} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.association :document_type, :as => :select %>
    <%= f.file_field :document_link%>

  </div>
    <%= f.button :submit, :class => "btn btn-success document-new document-submit" %>

<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Document type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= document.name %></td>
    <td><%= document.description %></td>
    <td><%= document.document_type_id %></td>
    <td><%= link_to 'Edit', edit_document_path(document), :class => "btn btn-mini btn-primary document-edit" %></td>
    <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger document-delete" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_document_path, :class => "btn btn-mini btn-success document-new" %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path, :class => "btn btn-primary document-edit" %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @document.name %>
</p>

<p>
  <b>Description:</b>
  <%= @document.description %>
</p>

<p>
  <b>Document type:</b>
  <%= @document.document_type_id %>
</p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>