config/routes.rb
HopeTest::Application.routes.draw do

  resources :admins

  resources :documents

  resources :links

  get "users/new"

  get '/about' => 'static_pages#about'

  get '/contact' => 'messages#new'

  resources :groups

  match '/events/search' => 'events#search', :method => 'post'

  match '/events/print' => 'events#print', :method => 'get'

  resources :events

  resources :users

  resources :links

  resources :sessions, only: [:new, :create, :destroy]

  resources :messages, only: [:new, :create]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'#, via: :delete

  get '/home' => 'static_pages#about'
  root :to => 'static_pages#about'

end

app/models/link.rb
class Link < ActiveRecord::Base
  @@result
  attr_accessible :link_type_id, :location, :name, :opening, :phone, :text, :url
  belongs_to :link_type


  def self.emergency
	all.keep_if do |l|
      l.link_type.position  == 1
    end
  end

  def self.non_emergency
	all.keep_if do |l|
      l.link_type.position  == 2
    end
  end

  def self.specific
	all.keep_if do |l|
      l.link_type.position  == 3
    end
  end

  def self.young_people
	all.keep_if do |l|
      l.link_type.position  == 4
    end
  end

  def self.adults
  all.keep_if do |l|
      l.link_type.position  == 5
    end
  end

  def self.older_people
  all.keep_if do |l|
      l.link_type.position  == 6
    end
  end

  def self.family
  all.keep_if do |l|
      l.link_type.position  == 7
    end
  end

  def self.housing
  all.keep_if do |l|
      l.link_type.position  == 8
    end
  end

  def self.financial_legal
  all.keep_if do |l|
      l.link_type.position  == 9
    end
  end

  def self.other
  all.keep_if do |l|
      l.link_type.position  == 10
    end
  end

end

app/models/link_type.rb
class LinkType < ActiveRecord::Base
  attr_accessible :position, :title
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.json
  def index
    @links = Link.all
    @emergency = Link.emergency
    @non_emergency = Link.non_emergency
    @specific = Link.specific
    @young_people = Link.young_people
    @adults = Link.adults
    @older_people = Link.older_people
    @family = Link.family
    @housing = Link.housing
    @financial_legal = Link.financial_legal
    @other = Link.other


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= simple_form_for(@link) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs link-form">
    <%= f.input :name %>
    <%= f.input :url %>
    <%= f.input :phone %>
    <%= f.input :location %>
    <%= f.input :opening %>
    <%= f.input :text, :as => :text, :input_html => { :rows => 3 } %>
    <%= f.association :link_type, :as => :select, :input_html => { :class => 'link-select' } %>
  </div>


    <%= f.button :submit, :class => 'btn-primary btn-large link-create', :id =>  'event-submit'  %>

        <%= link_to 'Back', events_path, :class => 'btn-success btn-large link-back' %>


<% end %>

app/views/links/_single_link.html.erb
<tr class="single-link">
    <td>
        <span class="link-name"><%= link.name %></span>
        <br>
        <a class="link-url" href="<%= link.url %>"><%= link.url %></a>
        <br>
        <span class="link-phone"><%= link.phone %></span>
    </td>
    <td>
        <span class="link-location"><%= link.location %></span>
        <br>
        <span class="link-opening"><%= link.opening %></span>
    </td>
    <td>
        <span class="link-text"><%= link.text %></span>
        <% if admin %>
    <span><%= link_to 'Edit', edit_link_path(link), :class => 'btn btn-primary btn-mini link-btn'  %></span>
    <span><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-mini link-btn' %></span>
    <% end %>
    </td>

  </tr>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<div class="scroll-containerXXX">
<h1 class="links-heading">Links</h1>
<% if admin %>
    <%= link_to 'New Link', new_link_path, :class => 'btn-success btn link-btn' %>
<% end %>
<table class="links-table">

    <tr class="links-table-section">
        <td>Emergency Links</td>
        <td></td>
        <td></td>
    </tr>
    <% @emergency.each do |link| %>
      <%= render :partial => 'single_link', :locals => {:link => link} %>
    <% end %>

    <tr class="links-table-section">
        <td>Non emergency Links</td>
        <td></td>
        <td></td>
    </tr>
    <% @non_emergency.each do |link| %>
      <%= render :partial => 'single_link', :locals => {:link => link} %>
    <% end %>

    <tr class="links-table-section">
        <td>Specific Links</td>
        <td></td>
        <td></td>
    </tr>
    <% @specific.each do |link| %>
      <%= render :partial => 'single_link', :locals => {:link => link} %>
    <% end %>

    <tr class="links-table-section">
        <td>Young People Links</td>
        <td></td>
        <td></td>
    </tr>
    <% @young_people.each do |link| %>
      <%= render :partial => 'single_link', :locals => {:link => link} %>
    <% end %>

    <tr class="links-table-section">
        <td>adults Links</td>
        <td></td>
        <td></td>
    </tr>
    <% @adults.each do |link| %>
      <%= render :partial => 'single_link', :locals => {:link => link} %>
    <% end %>

    <tr class="links-table-section">
        <td>Older People Links</td>
        <td></td>
        <td></td>
    </tr>
    <% @older_people.each do |link| %>
      <%= render :partial => 'single_link', :locals => {:link => link} %>
    <% end %>

    <tr class="links-table-section">
        <td>Family Links</td>
        <td></td>
        <td></td>
    </tr>
    <% @family.each do |link| %>
      <%= render :partial => 'single_link', :locals => {:link => link} %>
    <% end %>

    <tr class="links-table-section">
        <td>Housing Links</td>
        <td></td>
        <td></td>
    </tr>
    <% @housing.each do |link| %>
      <%= render :partial => 'single_link', :locals => {:link => link} %>
    <% end %>

    <tr class="links-table-section">
        <td>Financial and Legal Links</td>
        <td></td>
        <td></td>
    </tr>
    <% @financial_legal.each do |link| %>
      <%= render :partial => 'single_link', :locals => {:link => link} %>
    <% end %>



    <tr class="links-table-section">
        <td>Social / Other Links</td>
        <td></td>
        <td></td>
    </tr>
    <% @other.each do |link| %>
      <%= render :partial => 'single_link', :locals => {:link => link} %>
    <% end %>

</table>

<br />

</div>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<%= render :partial => "shared/notice" %>

<p>
  <b>Name:</b>
  <%= @link.name %>
</p>

<p>
  <b>Url:</b>
  <%= @link.url %>
</p>

<p>
  <b>Phone:</b>
  <%= @link.phone %>
</p>

<p>
  <b>Location:</b>
  <%= @link.location %>
</p>

<p>
  <b>Opening:</b>
  <%= @link.opening %>
</p>

<p>
  <b>Text:</b>
  <%= @link.text %>
</p>

<p>
  <b>Link type:</b>
  <%= @link.link_type_id %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>